// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "commits",
    columns: [
      {
        name: "relevantFiles",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
      { name: "commitSha", type: "text", notNull: true, defaultValue: "" },
      { name: "branchName", type: "text", notNull: true, defaultValue: "" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Commits = InferredTypes["commits"];
export type CommitsRecord = Commits & XataRecord;

export type DatabaseSchema = {
  commits: CommitsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Bruno-s-workspace-8rk1pv.eu-central-1.xata.sh/db/bucketline",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
